
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5279

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Intotech.Wheelo.Cmc.Api/Intotech.Wheelo.Dictionaries.Api.csproj", "Intotech.Wheelo.Cmc.Api"]
RUN dotnet restore "Intotech.Wheelo.Cmc.Api/Intotech.Wheelo.Dictionaries.Api.csproj"
COPY . .
WORKDIR "/src/Intotech.Wheelo.Cmc.Api"
RUN dotnet build "Intotech.Wheelo.Dictionaries.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Intotech.Wheelo.Dictionaries.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS http://*:5279
ENTRYPOINT ["dotnet", "Intotech.Wheelo.Dictionaries.Api.dll"]